# Generated by Django 4.1.4 on 2023-02-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='d_id',
            new_name='deparment_name',
        ),
    ]
